### ISSUE TITLE
Fix celluloid dependency issues

### ISSUE THREAD

**Issue by Startouf** [joekhoobyar/shoryuken-later#12]
Celluloid dependency locked to `~> 0.15.2`, hopefully the dependency can be removed/bumped to support same major version

**Comment by Startouf** [comment]
2017-05-03T07:47:04Z 29135 TID-46e3s [later] INFO: Starting
String can't be coerced into Float
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/gems/timers-4.0.4/lib/timers/timer.rb:81:in `+'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/gems/timers-4.0.4/lib/timers/timer.rb:81:in `reset'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/gems/timers-4.0.4/lib/timers/timer.rb:23:in `initialize'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/gems/timers-4.0.4/lib/timers/group.rb:51:in `new'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/gems/timers-4.0.4/lib/timers/group.rb:51:in `every'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/bundler/gems/shoryuken-later-9509c2d5289c/lib/shoryuken/later/cli.rb:64:in `start'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/bundler/gems/shoryuken-later-9509c2d5289c/lib/shoryuken/later/cli.rb:40:in `block in run'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/gems/shoryuken-3.0.6/lib/shoryuken/logging.rb:21:in `with_context'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/bundler/gems/shoryuken-later-9509c2d5289c/lib/shoryuken/later/cli.rb:38:in `run'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/bundler/gems/shoryuken-later-9509c2d5289c/bin/shoryuken-later:6:in `<top (required)>'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/bin/shoryuken-later:22:in `load'
/var/www/example-website-staging/shared/bundle/ruby/2.3.0/bin/shoryuken-later:22:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `load'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli/exec.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli.rb:335:in `exec'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli.rb:20:in `dispatch'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/cli.rb:11:in `start'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/exe/bundle:32:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
/usr/local/rvm/gems/ruby-2.3.3/gems/bundler-1.14.6/exe/bundle:24:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/bin/bundle:22:in `load'
/usr/local/rvm/gems/ruby-2.3.3/bin/bundle:22:in `<main>'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.3/bin/ruby_executable_hooks:15:in `<main>'
